// Package auth is password login (T-12 / FR-30) and who-labeled-what (FR-31).
//
// Off unless you configure users. With no users the whole app behaves exactly
// as before -- that is the "one person, own PC" case the tool started as, and
// adding a login screen to it would be pure friction. Configure users and every
// endpoint except /api/config and /api/auth/* needs a session cookie.
//
// Ported from the FastAPI service's services/auth.py, and the formats are frozen rather than
// modernised. Two of them are compatibility surfaces, not implementation
// details:
//
//   - the stored hash, because LABEL_TOOL_USERS entries generated by the
//     FastAPI service's `python -m backend.services.auth` are already in
//     people's config and have to keep working (the replacement generator is
//     the api binary's -hash-password flag);
//   - the session cookie, because a login issued before a deploy has to still
//     be a login after it.
//
// backend/tests/testdata/auth_vectors.json pins both, and auth_test.go checks this
// implementation against vectors Python produced.
//
// The comparison is deliberately not "whatever crypto library is nicest": it is
// PBKDF2-HMAC-SHA256 at 240,000 iterations with a 16-byte salt and a 32-byte
// derived key, because that is what is already on disk in people's config.
package auth

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	"golang.org/x/crypto/pbkdf2"
)

const (
	// Cookie is the session cookie's name.
	Cookie = "labeltool_session"
	// TTLSeconds is how long an issued session stays valid.
	TTLSeconds = 12 * 3600
	// Iterations is the PBKDF2 work factor. Changing it invalidates every
	// existing LABEL_TOOL_USERS entry, so it is not a knob.
	Iterations = 240_000

	saltBytes = 16
	keyBytes  = 32
)

type Auth struct{ secret []byte }

// New reads LABEL_TOOL_SECRET. Unset means a fresh random secret per start,
// i.e. everyone is signed out whenever the service restarts.
//
// That is the right default -- no secret sitting in a repo -- but it is worth
// setting once more than one instance can serve a request, or a session issued
// by one is rejected by the next.
func New() *Auth {
	if s := os.Getenv("LABEL_TOOL_SECRET"); s != "" {
		return &Auth{secret: []byte(s)}
	}
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		panic("auth: no entropy for a session secret: " + err.Error())
	}
	return &Auth{secret: []byte(hex.EncodeToString(buf))}
}

// NewWithSecret is for tests and for pinning the secret explicitly.
func NewWithSecret(secret string) *Auth { return &Auth{secret: []byte(secret)} }

// HashPassword produces a LABEL_TOOL_USERS value: pbkdf2$<iters>$<salt>$<key>.
func HashPassword(password string) string {
	salt := make([]byte, saltBytes)
	if _, err := rand.Read(salt); err != nil {
		panic("auth: no entropy for a password salt: " + err.Error())
	}
	return formatHash(password, salt, Iterations)
}

func formatHash(password string, salt []byte, iters int) string {
	dk := pbkdf2.Key([]byte(password), salt, iters, keyBytes, sha256.New)
	return fmt.Sprintf("pbkdf2$%d$%s$%s", iters, hex.EncodeToString(salt), hex.EncodeToString(dk))
}

// VerifyPassword reports whether password matches a stored hash. Every way the
// stored value can be malformed -- wrong algorithm, wrong field count,
// non-numeric iterations, non-hex salt -- is false rather than an error: the
// caller's response to all of them is the same rejection.
func VerifyPassword(password, stored string) bool {
	parts := strings.Split(stored, "$")
	if len(parts) != 4 || parts[0] != "pbkdf2" {
		return false
	}
	iters, err := strconv.Atoi(parts[1])
	if err != nil || iters <= 0 {
		return false
	}
	salt, err := hex.DecodeString(parts[2])
	if err != nil {
		return false
	}
	want, err := hex.DecodeString(parts[3])
	if err != nil {
		return false
	}
	dk := pbkdf2.Key([]byte(password), salt, iters, len(want), sha256.New)
	return subtle.ConstantTimeCompare(dk, want) == 1
}

// Users parses LABEL_TOOL_USERS ("alice:pbkdf2$...,bob:pbkdf2$...").
//
// Read per call, not cached, matching the Python behaviour: the value is split
// on the *first* colon only, since a hash contains "$" but never ":".
func Users() map[string]string {
	out := map[string]string{}
	for _, entry := range strings.Split(os.Getenv("LABEL_TOOL_USERS"), ",") {
		name, stored, found := strings.Cut(strings.TrimSpace(entry), ":")
		if found && name != "" && stored != "" {
			out[name] = stored
		}
	}
	return out
}

// Enabled reports whether this deployment has any users at all. False means
// there is no login and every endpoint is open to whoever can reach it.
func Enabled() bool { return len(Users()) > 0 }

// Check verifies a username and password.
//
// A missing user is still hashed against a throwaway value, so a wrong username
// and a wrong password take the same time to reject -- otherwise the response
// time enumerates valid usernames.
func Check(username, password string) bool {
	stored, ok := Users()[username]
	if !ok {
		stored = HashPassword("no-such-user")
	}
	return VerifyPassword(password, stored)
}

func (a *Auth) sign(body string) string {
	mac := hmac.New(sha256.New, a.secret)
	mac.Write([]byte(body))
	return hex.EncodeToString(mac.Sum(nil))
}

// Issue mints a session token: <user>|<expiry unix seconds>|<signature>.
func (a *Auth) Issue(user string) string {
	body := fmt.Sprintf("%s|%d", user, time.Now().Unix()+TTLSeconds)
	return body + "|" + a.sign(body)
}

// Identify returns the user a token proves, or "" for none. Absent, tampered,
// expired and malformed all collapse to the same answer because the caller
// responds to all of them with the same 401.
func (a *Auth) Identify(token string) string {
	if token == "" {
		return ""
	}
	// Split from the right, not the left: the signature and expiry are the last
	// two fields, so a username containing "|" can never shift them.
	sigAt := strings.LastIndex(token, "|")
	if sigAt < 0 {
		return ""
	}
	expAt := strings.LastIndex(token[:sigAt], "|")
	if expAt < 0 {
		return ""
	}
	user, exp, sig := token[:expAt], token[expAt+1:sigAt], token[sigAt+1:]
	if !hmac.Equal([]byte(sig), []byte(a.sign(user+"|"+exp))) {
		return ""
	}
	deadline, err := strconv.ParseInt(exp, 10, 64)
	if err != nil || deadline <= time.Now().Unix() {
		return ""
	}
	return user
}
